name: thy_cadet_app
description: "THY Cadet Program mobile application with psychometric tests and AI integration"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^15.2.0
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # UI & Design
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  cached_network_image: ^3.3.0
  
  # Audio & Animation
  audioplayers: ^5.2.1
  
  # Models & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Utilities
  shared_preferences: ^2.2.2
  http: ^1.1.2
  intl: ^0.20.2
  
  # Localization
  flutter_localizations:
    sdk: flutter

  flutter_svg: ^2.0.10
  flutter_custom_clippers: ^2.1.0
  lottie: ^3.1.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/audio/
    - assets/animations/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700 