description: Flutter-based THY Cadet Program app with gamified psychometric tests,
  AI feedback, and multi-airline support.
game_modules:
- attention_test
- memory_test
- spatial_perception
- psychomotor_coordination
name: thy_cadet_flutter_app
platform: mobile
screens:
- /splash
- /login
- /signup
- /home
- /course/:id
- /course/:id/psychometric
- /course/:id/psychometric/attention
- /result
- /profile
structure:
  lib:
    core:
    - theme
    - constants
    - helpers
    features:
      auth:
      - login
      - signup
      courses:
      - course_list
      - course_detail
      games:
      - attention
      - memory
      - spatial
      - motor
      profile: []
      result: []
    main.dart: entry point
    services:
    - firebase_service
    - ai_service
    shared:
    - widgets
    - extensions
    - components
technologies:
  ai_future:
  - OpenAI
  - Veo3
  - chatbot assistant
  architecture:
  - Clean Architecture
  - Feature-Based
  backend:
  - Firebase Auth
  - Firestore
  - Storage
  canvas_engine: CustomPainter + GameEngine abstraction
  framework: Flutter
  language: Dart (null safety)
  state_management:
  - Riverpod
  - Bloc
  testing:
  - flutter_test
  - mockito
  - integration_test
